### ISSUE TITLE
Enable importing .ksp files from folders (#400) broke some imports here (possible old math library related)

### ISSUE THREAD

**Issue by dxmachina** [nojanath/SublimeKSP#447]
This commit specifically broke code that I'm maintaining here, possibly only related to the import of the old Big Bob math library. https://github.com/nojanath/SublimeKSP/commit/63a497fd51c7365b9a1d9c3c0685a077375b49b7

The line is simply: `import "KSPMathV702.ksp"`

Yields: Syntax error! (line 2279)
../common/external/KSPMathV702.ksp:4625 

Release 1.17.0 is fine

**Comment by mkruselj** [comment]
Hmmm, I have some code that imports that same file in exactly the same way and it all works fine still... Weird!

**Comment by dxmachina** [comment]
Wow, really? Hmm.

It's obviously easy enough just to use the right commit when I need to get back to that code, but I figured a lot of people are maintaining code with the same library.

I did try a bunch of path simplifying to make sure it wasn't that. This was all on macOS.

Will take another look when I have some time.

**Comment by mkruselj** [comment]
Can you try with the very latest commit, please? Unsure if it'd fix but worth a shot I guess...

**Comment by dxmachina** [comment]
Unfortunately, still an issue with the latest commit here. When I find some time I will see about debugging it here as well.

**Comment by mkruselj** [comment]
@dxmachina Would you mind DMing me the exact code which reproduces this issue? As minimal as possible. Thanks!

**Comment by dxmachina** [comment]
@mkruselj I'll take a look again when back after the 1st, but if I recall it was only a matter of importing the library as above. Don't think I even needed to call a function to run into the error on compilation

**Comment by mkruselj** [comment]
Right. That's weird, because that exact math lib version imports just fine over here...

Happy new year!

**Comment by dxmachina** [comment]
Yep, going to have to dig in a bit more here to figure out the actual issue. I _was_ able to import into a new file and (after remembering how this thing worked with the math modes) call some of the functions without issue. So we're seeing the same behaviour.

BUT, I do have a number of  legacy projects that made very extensive use of this library that still won't compile without using older commits, so it may be more related to a specific function, or perhaps some kind of issue with nested macros/functions. Will get you a proper simple repro once I sort it out.

NBD though... easy enough to swap out with an older commit to compile these when necessary.

Happy New Year to you as well!

**Comment by mkruselj** [comment]
You shouldn't need to faff around with swapping out commits just to make older stuff work, so yeah, more exploratory digging to find the root cause would be really welcome...

**Comment by mkruselj** [comment]
Curious. Good to know. But if I remember correctly the compiler actually has a function that is executed on file load that is supposed to fix the line endings. However this was apparently not working for the past several versions due to the incorrect way I was monitoring the plugin's load state. This should be fixed as of commit 5af048ab, so worth checking your math lib file before you fixed line endings if it works from that commit onward...

**Comment by mkruselj** [comment]
@dxmachina Just a reminder ping if you could verify the above? Thanks!

**Comment by mkruselj** [comment]
@dxmachina And another ping, I don't want to close this issue without having the above confirmed. Thanks!

**Comment by dxmachina** [comment]
Apologies for the delay @mkruselj   

That commit did not resolve it for me using the previous state of the math library but I haven’t spent any time further debugging after fixing the line endings. 

I’ll try to get you more info on it soon if you want to leave open.

**Comment by mkruselj** [comment]
Yeah I do want to resolve it. If EOL conversion happened, you should see a message in Sublime Text's console during file open, just FYI.

**Comment by mkruselj** [comment]
@dxmachina OK, I think my prior attempt at a fix for detecting the Sublime plugin loaded state was wrong. I noticed this when I was pasting valid KSP code in an empty untitled file, and syntax coloring would not automatically update (as it was expected).

Turns out, I completely did not understand what is going on with global variables in Python. But now I do. Can you please check one more time with commit 188912d? I would hope that the automatic fix for mixed EOLs in a file should kick in now!

**Comment by mkruselj** [comment]
@dxmachina I would love to have your confirmation if the currently opened PR fixes this issue on your end as well. I have the original download of math library working now but having it double checked is always preferred. I don't want to merge the PR without the confirmation. Thanks!

**Comment by dxmachina** [comment]
@mkruselj Yes! You've done it, I believe _all_ my old repos compile now without any manual intervention. Thanks for staying on it. Relatively obscure issue but probably does affect a fair amount of older projects.
